### ISSUE TITLE
The name of this repository is incorrectly spelled

### ISSUE THREAD

**Issue by nyuszika7h** [Mikaela/freenode-harassement#1]
I just noticed this. It should be *harassment*, not _harass**e**ment_.

**Comment by Mikaela** [comment]
I don't think it's that important to change after these months.

**Comment by nyuszika7h** [comment]
It [shouldn't cause any problems](https://help.github.com/articles/renaming-a-repository/), but okay then.

**Comment by Mikaela** [comment]
Thinking it more, the name is quite important as it encourages me to mispell the word always, so I am changing it soon.

**Comment by Mikaela** [comment]
Done.
